app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: root:mima123@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenCons: 114

jwt:
  signingKey: gogofly.cn #签名使用的key

redis:
  addr: localhost:6379
  DB: 0
  Password: ""

tgbot:
  Token: "7384710909:AAEGcRFtwuMnoqaCOLA_vRvDE2zcN7ISblI"