app:
  name: CurrencyExchangeApp
  port: :3000

database:
  dsn: root:mima1233@tcp(localhost:3306)/test?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdleConns: 11
  MaxOpenCons: 114

jwt:
  signingKey: gogofly.cn #签名使用的key

redis:
  addr: localhost:6379
  DB: 0
  Password: ""

tgbot:
  Token: "7384710909:AAEGcRFtwuMnoqaCOLA_vRvDE2zcN7ISblI"
  chatID: -4102331731     # app群chatID: -4102331731   测试Rebot群 ：-1002421880670
  hour: 18                   # 晚上6点
  min: 39                    # 39分
  sec: 10                    # 10秒

