definitions:
  models.Article:
    properties:
      content:
        description: 没有指定的默认是longtext类型
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: integer
      preview:
        type: string
      title:
        description: 类型是varchar  gorm:"size:255" 长度是255个字符 gorm:"size:10" 类型是varchar
          长度是10
        type: string
      updatedAt:
        type: string
    required:
    - content
    - preview
    - title
    type: object
  models.Banner:
    properties:
      url:
        type: string
    type: object
  models.Banners:
    properties:
      bannerx:
        items:
          $ref: '#/definitions/models.Banner'
        type: array
    type: object
  models.JSONResult:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        description: '`gorm:"index"`'
        type: string
      id:
        type: integer
      password:
        type: string
      token:
        type: string
      uid:
        type: integer
      updatedAt:
        type: string
      username:
        type: string
    type: object
  models.UserBody:
    properties:
      age:
        description: 用户年龄（可选）
        example: 25
        type: integer
      password:
        description: 用户年龄（必填）
        example: "123"
        type: string
      username:
        description: 用户名（必填）
        example: admin
        type: string
    required:
    - password
    - username
    type: object
host: 192.168.9.109:3000
info:
  contact:
    email: support@swagger.io
    name: Like API
  title: Swagger Example API
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: json
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserBody'
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
      summary: 登录
      tags:
      - 接口文档
  /api/banners:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 成功响应
          schema:
            allOf:
            - $ref: '#/definitions/models.JSONResult'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/models.Banners'
                  - properties:
                      bannerx:
                        items:
                          $ref: '#/definitions/models.Banner'
                        type: array
                    type: object
              type: object
      summary: 获取Banner图列表
      tags:
      - 接口文档
  /api/exchangeRates/articles:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Article'
            type: array
      summary: 获取文章列表
      tags:
      - 接口文档
    post:
      consumes:
      - application/json
      parameters:
      - description: 传json数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.UserBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      summary: 注册
      tags:
      - 接口文档
  /api/exchangeRates/articles/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Article'
      summary: 根据ID获取新闻
      tags:
      - 接口文档
  /api/hotgames:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
      summary: 获取热门图列表
      tags:
      - 接口文档
swagger: "2.0"
